version: "3.1"

services:
  node:
    build: docker/node
    container_name: bnt_node
    volumes:
      - "./:/home/node/app:rw,consistent"
    working_dir: "/home/node/app"
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bnt_phpmyadmin
    ports:
      - "8001:80"
    depends_on:
      - mysql
    networks:
      - proxy
    environment:
      PMA_HOST: mysql

  mysql:
    image: mysql:5.7
    container_name: bnt_mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - proxy
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookntalk
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "1082:3306"

  maildev:
    image: djfarrelly/maildev
    container_name: bnt_maildev
    ports:
      - "1025:25"
      - "1080:80"
networks:
  proxy:
    driver: bridge
